import { createClient } from 'https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/+esm';
import { SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY } from './config.js';

const supabase=createClient(SUPABASE_URL,SUPABASE_PUBLISHABLE_KEY,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});
const $=(s,r=document)=>r.querySelector(s);
let user=null,access=null,subscription=null,busy=false;

function ensureStyles(){if(document.querySelector('link[data-ai-module]'))return;const l=document.createElement('link');l.rel='stylesheet';l.href='./css/ai-module.css?v=20260913-0060';l.dataset.aiModule='1';document.head.appendChild(l)}
function esc(v=''){return String(v).replace(/[&<>'\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function hasAccess(){return (access?.role==='dono'&&access?.status==='ativo')||subscription?.status==='active'}
function accessLabel(){if(access?.role==='dono'&&access?.status==='ativo')return'Conta dono';if(subscription?.status==='active')return'Plano IA ativo';return'Acesso bloqueado'}
function goSubscription(){document.querySelector('[data-page="subscription"]')?.click()}

function ensureUI(){const page=$('#aiPage');if(!page)return;page.innerHTML=`<div class="ai-shell"><div class="ai-head"><div class="ai-brand"><div class="ai-orb">✦</div><div><h2>IA Financeira RENOVA</h2><p>Análise inteligente conectada aos seus dados financeiros.</p></div></div><span id="aiAccessBadge" class="ai-access-badge locked">Verificando acesso...</span></div><div id="aiBody" class="ai-body"></div><div id="aiComposer" class="ai-composer hidden"><div class="ai-composer-inner"><textarea id="aiInput" class="ai-input" rows="1" placeholder="Pergunte sobre seus gastos, orçamento, contas, cartões ou metas..."></textarea><button id="aiSend" class="ai-send" type="button" aria-label="Enviar">➤</button></div><div class="ai-note">A IA analisa seus dados do RENOVA. Confirme informações importantes antes de tomar decisões financeiras.</div></div></div>`}

function renderGate(){const body=$('#aiBody'),composer=$('#aiComposer'),badge=$('#aiAccessBadge');if(!body)return;const allowed=hasAccess();badge.textContent=accessLabel();badge.classList.toggle('locked',!allowed);composer.classList.toggle('hidden',!allowed);if(!allowed){body.innerHTML=`<div class="ai-gate"><div class="ai-gate-card"><div class="ai-orb">✦</div><h3>Desbloqueie a IA Financeira</h3><p>Seu acesso gratuito continua funcionando normalmente. A IA Financeira é liberada para assinaturas ativas, enquanto a conta dono possui acesso global.</p><div class="ai-gate-actions"><button class="primary-btn" id="aiViewSubscription" type="button">Ver assinatura</button></div></div></div>`;$('#aiViewSubscription')?.addEventListener('click',goSubscription);return}renderWelcome()}
function renderWelcome(){const body=$('#aiBody');if(!body)return;body.innerHTML=`<div class="ai-welcome"><div class="ai-orb">✦</div><h3>Como posso ajudar com suas finanças?</h3><p>Eu consigo analisar seus lançamentos, contas, cartões, orçamento e metas usando os dados atuais do Minhas Finanças RENOVA.</p></div><div class="ai-prompts"><button class="ai-prompt" type="button">Como está minha situação financeira este mês?</button><button class="ai-prompt" type="button">Onde estou gastando mais?</button><button class="ai-prompt" type="button">Como posso organizar melhor meu orçamento?</button><button class="ai-prompt" type="button">Qual meta financeira devo priorizar?</button></div><div id="aiMessages" class="ai-messages"></div>`;document.querySelectorAll('.ai-prompt').forEach(b=>b.addEventListener('click',()=>sendText(b.textContent.trim())))}
function messagesHost(){return $('#aiMessages')}
function addMessage(role,text){const host=messagesHost();if(!host)return;const row=document.createElement('div');row.className=`ai-message ${role}`;row.innerHTML=`<div class="ai-bubble">${esc(text)}</div>`;host.appendChild(row);scrollBottom();return row}
function addThinking(){const host=messagesHost();if(!host)return null;const row=document.createElement('div');row.className='ai-message assistant';row.innerHTML='<div class="ai-bubble"><span class="ai-thinking"><i></i><i></i><i></i></span></div>';host.appendChild(row);scrollBottom();return row}
function scrollBottom(){const body=$('#aiBody');if(body)requestAnimationFrame(()=>{body.scrollTop=body.scrollHeight})}
function setBusy(v){busy=v;const btn=$('#aiSend'),input=$('#aiInput');if(btn)btn.disabled=v;if(input)input.disabled=v}
async function errorMessage(error){try{if(error?.context?.json){const p=await error.context.json();if(p?.error)return p.error}}catch{}return error?.message||'Não foi possível falar com a IA agora.'}

async function sendText(raw){const text=String(raw||'').trim();if(!text||busy||!hasAccess())return;const input=$('#aiInput');if(input){input.value='';input.style.height='auto'}addMessage('user',text);const thinking=addThinking();setBusy(true);try{const {data,error}=await supabase.functions.invoke('finance-ai',{body:{message:text}});thinking?.remove();if(error){addMessage('system',await errorMessage(error));return}if(data?.error){addMessage('system',data.error);return}addMessage('assistant',data?.answer||'Não consegui gerar uma resposta agora.')}catch(e){thinking?.remove();addMessage('system',e?.message||'Erro ao consultar a IA.')}finally{setBusy(false);input?.focus()}}

async function loadAccess(){if(!user)return;const [{data:a},{data:s}]=await Promise.all([supabase.from('user_access').select('role,status').eq('user_id',user.id).maybeSingle(),supabase.from('ai_subscriptions').select('plan_code,status,current_period_end').eq('user_id',user.id).order('created_at',{ascending:false}).limit(1).maybeSingle()]);access=a;subscription=s;renderGate()}
function bind(){const input=$('#aiInput'),send=$('#aiSend');send?.addEventListener('click',()=>sendText(input?.value));input?.addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();sendText(input.value)}});input?.addEventListener('input',()=>{input.style.height='auto';input.style.height=`${Math.min(120,input.scrollHeight)}px`})}

ensureStyles();ensureUI();bind();const {data:{session}}=await supabase.auth.getSession();user=session?.user||null;if(user)await loadAccess();supabase.auth.onAuthStateChange((_e,s)=>{user=s?.user||null;access=null;subscription=null;if(user)setTimeout(loadAccess,0);else renderGate()});
