import { createClient } from 'https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/+esm';
import { SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY } from './config.js';

const supabase=createClient(SUPABASE_URL,SUPABASE_PUBLISHABLE_KEY,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});
const $=(s,r=document)=>r.querySelector(s);
const money=(v=0)=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(Number(v)||0);
const esc=(v='')=>String(v).replace(/[&<>'\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
let user=null,controller=null,currentPlan=null,busy=false;

function ensureStyles(){if(document.querySelector('link[data-checkout-module]'))return;const l=document.createElement('link');l.rel='stylesheet';l.href='./css/checkout-module.css?v=20260913-0081';l.dataset.checkoutModule='1';document.head.appendChild(l)}
function toast(message,type='ok'){const el=$('#toast');if(!el)return;el.textContent=message;el.className=`toast show ${type}`;clearTimeout(toast.timer);toast.timer=setTimeout(()=>el.className='toast',3600)}
function ensureModal(){if($('#renovaCheckoutModal'))return;document.body.insertAdjacentHTML('beforeend',`<div id="renovaCheckoutModal" class="renova-checkout-modal hidden" role="dialog" aria-modal="true" aria-labelledby="renovaCheckoutTitle"><div class="renova-checkout-backdrop" data-checkout-close></div><div class="renova-checkout-card"><div class="renova-checkout-head"><div><span class="eyebrow">CHECKOUT TRANSPARENTE</span><h2 id="renovaCheckoutTitle">Finalizar pagamento</h2><p>Escolha Pix, cartão ou boleto sem sair do RENOVA.</p></div><button class="icon-btn renova-checkout-close" data-checkout-close type="button" aria-label="Fechar">×</button></div><div id="renovaCheckoutBody" class="renova-checkout-body"></div></div></div>`)}
function setOpen(v){const m=$('#renovaCheckoutModal');if(!m)return;m.classList.toggle('hidden',!v);document.body.classList.toggle('modal-open',v)}
async function destroyBrick(){if(controller){try{await controller.unmount()}catch{}controller=null}const host=$('#renovaPaymentBrick');if(host)host.innerHTML=''}
async function closeCheckout(){if(busy)return;await destroyBrick();currentPlan=null;setOpen(false)}
function summary(plan){return `<div class="renova-checkout-summary"><div><span>Plano</span><strong>${esc(plan.name)}</strong></div><div><span>Mensalidade • 30 dias</span><strong>${money(plan.base_price)}</strong></div>${Number(plan.setup_amount)>0?`<div><span>Implantação inicial</span><strong>${money(plan.setup_amount)}</strong></div>`:''}<div class="renova-checkout-total"><span>Total desta cobrança</span><strong>${money(plan.total)}</strong></div></div>`}
function configError(message){const body=$('#renovaCheckoutBody');if(!body)return;body.innerHTML=`<div class="renova-checkout-error"><strong>Checkout ainda não configurado</strong><div>${esc(message||'Não foi possível iniciar o Mercado Pago.')}</div></div>`}

function loadSdk(){return new Promise((resolve,reject)=>{if(window.MercadoPago)return resolve(window.MercadoPago);const existing=document.querySelector('script[data-mercado-pago-sdk]');if(existing){existing.addEventListener('load',()=>resolve(window.MercadoPago),{once:true});existing.addEventListener('error',()=>reject(new Error('Falha ao carregar o SDK do Mercado Pago.')),{once:true});return}const s=document.createElement('script');s.src='https://sdk.mercadopago.com/js/v2';s.async=true;s.dataset.mercadoPagoSdk='1';s.onload=()=>resolve(window.MercadoPago);s.onerror=()=>reject(new Error('Falha ao carregar o SDK do Mercado Pago.'));document.head.appendChild(s)})}

async function edge(body){const {data,error}=await supabase.functions.invoke('mercado-pago-transparent-checkout',{body});if(error){let message=error.message||'Falha no checkout.';try{if(error.context?.json){const payload=await error.context.json();message=payload?.message||payload?.error||message}}catch{}throw new Error(message)}if(data?.error)throw new Error(data.message||data.error);return data}

function paymentResult(data){const body=$('#renovaCheckoutBody');if(!body)return;const status=String(data?.status||'pending').toLowerCase();const approved=status==='approved';const pending=['pending','in_process','in_mediation'].includes(status);let title=approved?'Pagamento aprovado ✅':pending?'Pagamento aguardando confirmação':'Pagamento não aprovado';let text=approved?'Seu pagamento foi aprovado. O plano será liberado pelo webhook e o período terá 30 dias.':pending?'Assim que o Mercado Pago confirmar o pagamento, o acesso será liberado automaticamente.':'O Mercado Pago não aprovou esta tentativa. Você pode fechar e tentar novamente.';let extra='';if(data?.qr_code||data?.qr_code_base64){extra=`<div class="renova-pix">${data.qr_code_base64?`<img src="data:image/png;base64,${esc(data.qr_code_base64)}" alt="QR Code Pix">`:''}${data.qr_code?`<div class="renova-pix-code"><textarea id="renovaPixCode" readonly>${esc(data.qr_code)}</textarea><button class="ghost-btn" id="copyPixCode" type="button">Copiar Pix</button></div>`:''}</div>`}if(data?.ticket_url){extra+=`<div class="renova-result-actions"><a class="primary-btn" href="${esc(data.ticket_url)}" target="_blank" rel="noopener">Abrir boleto</a></div>`}body.innerHTML=`${currentPlan?summary(currentPlan):''}<div class="renova-payment-result ${approved?'approved':pending?'pending':''}"><strong>${title}</strong><div>${text}</div>${extra}<div class="renova-result-actions"><button class="ghost-btn" id="refreshPaymentAccess" type="button">Atualizar meu acesso</button><button class="ghost-btn" data-checkout-close type="button">Fechar</button></div></div>`;$('#copyPixCode')?.addEventListener('click',async()=>{const code=$('#renovaPixCode')?.value||'';try{await navigator.clipboard.writeText(code);toast('Código Pix copiado.')}catch{toast('Selecione e copie o código Pix.','error')}});$('#refreshPaymentAccess')?.addEventListener('click',()=>location.reload())}

async function renderBrick(config){const body=$('#renovaCheckoutBody');if(!body)return;currentPlan=config.plan;body.innerHTML=`${summary(config.plan)}<div id="renovaPaymentBrick" class="renova-brick-wrap"></div><div class="renova-checkout-security">Pagamento processado pelo Mercado Pago. O RENOVA não armazena o número do seu cartão. A liberação ocorre somente após o pagamento ficar aprovado.</div>`;try{const MercadoPago=await loadSdk();if(!MercadoPago)throw new Error('SDK do Mercado Pago indisponível.');const mp=new MercadoPago(config.public_key,{locale:'pt-BR'});const bricks=mp.bricks();controller=await bricks.create('payment','renovaPaymentBrick',{initialization:{amount:Number(config.plan.total),payer:{email:user?.email||''}},customization:{paymentMethods:{creditCard:'all',bankTransfer:'all',ticket:'all'}},callbacks:{onReady:()=>{},onError:error=>{console.error('Mercado Pago Brick',error);toast('O Mercado Pago encontrou um erro no formulário.','error')},onSubmit:({formData})=>new Promise(async(resolve,reject)=>{if(busy)return reject(new Error('Pagamento já em processamento.'));busy=true;try{const data=await edge({action:'pay',plan_code:config.plan.code,form_data:formData});await destroyBrick();paymentResult(data);resolve(data)}catch(error){const host=$('#renovaPaymentBrick');if(host)host.insertAdjacentHTML('beforebegin',`<div class="renova-checkout-error" style="margin-bottom:12px"><strong>Não foi possível processar</strong><div>${esc(error?.message||'Erro no pagamento.')}</div></div>`);toast(error?.message||'Erro no pagamento.','error');reject(error)}finally{busy=false}})}})}catch(error){configError(error?.message||'Falha ao carregar o Checkout Transparente.')}}

async function openCheckout(planCode){if(!user){toast('Faça login para escolher um plano.','error');return}await destroyBrick();ensureModal();setOpen(true);const body=$('#renovaCheckoutBody');body.innerHTML='<div class="renova-checkout-loading"><strong>Preparando checkout seguro...</strong><div>Carregando as formas de pagamento.</div></div>';try{const config=await edge({action:'config',plan_code:planCode});await renderBrick(config)}catch(error){configError(error?.message||'Não foi possível preparar o checkout.')}}

function capturePlanClick(e){const btn=e.target.closest?.('[data-plan-action]');if(!btn)return;e.preventDefault();e.stopPropagation();e.stopImmediatePropagation();openCheckout(btn.dataset.planAction)}
document.addEventListener('click',capturePlanClick,true);document.addEventListener('click',e=>{if(e.target.closest?.('[data-checkout-close]'))closeCheckout()});document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!$('#renovaCheckoutModal')?.classList.contains('hidden'))closeCheckout()});

ensureStyles();ensureModal();const {data:{session}}=await supabase.auth.getSession();user=session?.user||null;supabase.auth.onAuthStateChange((_e,s)=>{user=s?.user||null});
