import { createClient } from 'https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/+esm';
import { SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY } from './config.js';

window.RENOVA_PLANS_UI_ACTIVE=true;

const supabase=createClient(SUPABASE_URL,SUPABASE_PUBLISHABLE_KEY,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});
const $=(s,r=document)=>r.querySelector(s);
const money=(v=0)=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(Number(v)||0);
const dateBR=v=>v?new Intl.DateTimeFormat('pt-BR').format(new Date(v)):'—';
const esc=(v='')=>String(v).replace(/[&<>'\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
let user=null,accessRow=null,entitlement=null,plans=[],trial=null,refProfile=null,referrals=[],commissions=[],adminUsers=[],adminSubs=[],accessChanges=[];

function ensureStyles(){if(document.querySelector('link[data-plans-module]'))return;const l=document.createElement('link');l.rel='stylesheet';l.href='./css/plans-module.css?v=20260913-0080';l.dataset.plansModule='1';document.head.appendChild(l)}
function toast(message,type='ok'){const el=$('#toast');if(!el)return;el.textContent=message;el.className=`toast show ${type}`;clearTimeout(toast.timer);toast.timer=setTimeout(()=>el.className='toast',3400)}
function isOwner(){return accessRow?.role==='dono'&&accessRow?.status==='ativo'}
function featureList(plan){const f=plan?.features||{};const items=[];if(f.transactions)items.push('Movimentações, contas e dashboard');if(f.cards)items.push('Cartões, orçamentos e metas');if(f.long_term_planning)items.push('Planejamento de longo prazo');if(f.ai_local)items.push('Modo Análise Local RENOVA');if(f.ai_training)items.push('Central própria de treinamento');if(f.business_workspace)items.push(`Workspace empresarial • até ${Number(plan.user_limit||1)} usuários`);if(f.ai_chat)items.push('Chat IA preparado para provedor configurado');return items.slice(0,6)}
function modeLabel(mode){return({owner:'Conta dono',trial:'Teste RENOVA',paid:'Plano ativo',business:'Business ativo',limited:'Acesso limitado'})[mode]||mode||'Acesso'}
function remainingDays(end){if(!end)return null;return Math.max(0,Math.ceil((new Date(end).getTime()-Date.now())/86400000))}

async function captureReferral(){const u=new URL(location.href);const code=u.searchParams.get('ref');if(code){localStorage.setItem('renova_referral_code',code.trim());u.searchParams.delete('ref');history.replaceState({},'',u.toString())}if(!user)return;const pending=localStorage.getItem('renova_referral_code');if(!pending)return;const {error}=await supabase.rpc('register_referral',{p_code:pending});if(!error)localStorage.removeItem('renova_referral_code')}

async function loadCore(){if(!user)return;const [a,e,p,t,r,refs,comms]=await Promise.all([
  supabase.from('user_access').select('role,status,email').eq('user_id',user.id).maybeSingle(),
  supabase.rpc('get_my_plan_access'),
  supabase.from('ai_subscription_plans').select('code,name,price,reference_price,description,promise,features,user_limit,setup_price,setup_reference_price,referral_rate,is_active,is_public,sort_order').eq('is_active',true).eq('is_public',true).order('sort_order'),
  supabase.from('user_trials').select('started_at,ends_at,status,converted_at').eq('user_id',user.id).maybeSingle(),
  supabase.from('referral_profiles').select('referral_code,commission_rate,is_active').eq('user_id',user.id).maybeSingle(),
  supabase.from('referrals').select('id,status,created_at,referred_user_id').eq('referrer_user_id',user.id).order('created_at',{ascending:false}),
  supabase.from('referral_commissions').select('id,commission_amount,status,earned_at,plan_code,payment_id').eq('referrer_user_id',user.id).order('earned_at',{ascending:false}).limit(200)
]);
  accessRow=a.data||null;entitlement=e.data||null;plans=p.data||[];trial=t.data||null;refProfile=r.data||null;referrals=refs.data||[];commissions=comms.data||[];
  if(isOwner())await loadAdmin();
}

async function loadAdmin(){const [u,s,c]=await Promise.all([
  supabase.from('user_access').select('user_id,email,role,status,created_at').order('created_at',{ascending:false}),
  supabase.from('ai_subscriptions').select('user_id,plan_code,status,current_period_end,provider,updated_at').order('updated_at',{ascending:false}),
  supabase.from('plan_access_changes').select('target_user_id,from_plan_code,to_plan_code,source,starts_at,ends_at,note,created_at').order('created_at',{ascending:false}).limit(30)
]);adminUsers=u.data||[];adminSubs=s.data||[];accessChanges=c.data||[]}

function subscriptionFor(uid){return adminSubs.find(s=>s.user_id===uid&&s.status==='active')||adminSubs.find(s=>s.user_id===uid)||null}
function currentAccessCard(){const mode=entitlement?.mode||'limited',days=remainingDays(entitlement?.expires_at);return `<div class="plans-hero"><div><span class="eyebrow">SEU ACESSO</span><h2>${esc(entitlement?.plan_name||modeLabel(mode))}</h2><p>${mode==='owner'?'Acesso administrativo global ao Minhas Finanças RENOVA.':mode==='trial'?'Você está no período gratuito de 14 dias para conhecer a ferramenta.':mode==='limited'?'Seu período de teste ou plano pago não está ativo. Seus dados permanecem preservados.':'Seu acesso está ativo e será mantido até o fim do período pago.'}</p>${mode==='trial'?`<div class="trial-progress"><i style="width:${Math.max(0,Math.min(100,((14-(days??0))/14)*100))}%"></i></div>`:''}</div><div class="plan-status"><span class="plan-status-badge ${mode==='limited'?'limited':''}">${esc(modeLabel(mode))}</span><strong>${entitlement?.expires_at?`até ${dateBR(entitlement.expires_at)}`:'Sem vencimento'}</strong><span>${days!==null?`${days} dia(s) restante(s)`:mode==='owner'?'Conta principal':' '}</span></div></div>`}

function planCards(){return `<section class="plans-section"><div><span class="eyebrow">PLANOS RENOVA</span><h3>Evolua conforme sua necessidade</h3><p>Comece com gestão financeira acessível e avance para análise e estrutura empresarial.</p></div><div class="plans-grid">${plans.map(p=>{const cls=p.code==='renova_analise'?'recommended':p.code==='renova_business'?'business':'';const current=entitlement?.plan_code===p.code;return `<article class="plan-card ${cls}">${p.code==='renova_analise'?'<span class="plan-ribbon">MAIS RECOMENDADO</span>':''}<div><h4>${esc(p.name)}</h4><div class="plan-price"><strong>${money(p.price)}</strong><span>/ 30 dias</span></div></div><div class="plan-description">${esc(p.description||p.promise||'')}</div>${Number(p.setup_price||0)>0?`<div class="plan-setup">Implantação de lançamento: <strong>${money(p.setup_price)}</strong></div>`:''}<div class="plan-features">${featureList(p).map(x=>`<span>${esc(x)}</span>`).join('')}</div><button class="${current?'ghost-btn':'primary-btn'} full plan-action" data-plan-action="${esc(p.code)}" type="button">${current?'Renovar plano':'Escolher plano'}</button></article>`}).join('')}</div><p class="plans-note">Os pagamentos serão processados pelo Checkout Transparente. Pix, cartão ou boleto liberam o acesso somente após confirmação de pagamento aprovado.</p></section>`}

function referralBlock(){if(!refProfile)return'';const available=commissions.filter(c=>c.status==='available').reduce((s,c)=>s+Number(c.commission_amount||0),0),paid=commissions.filter(c=>c.status==='paid').reduce((s,c)=>s+Number(c.commission_amount||0),0),activeRefs=referrals.filter(r=>r.status==='active').length;const base=`${location.origin}${location.pathname}?ref=${encodeURIComponent(refProfile.referral_code)}`;return `<section class="referral-card"><div><span class="eyebrow">INDIQUE E GANHE</span><h3>Receba comissão recorrente</h3><p>Quando uma pessoa indicada renovar um plano pago, a comissão é registrada automaticamente enquanto a indicação permanecer válida.</p><div class="referral-code-row"><input id="referralLink" readonly value="${esc(base)}"><button class="ghost-btn" id="copyReferral" type="button">Copiar link</button></div></div><div class="referral-stats"><div class="referral-stat"><span>Indicados</span><strong>${referrals.length}</strong></div><div class="referral-stat"><span>Ativos</span><strong>${activeRefs}</strong></div><div class="referral-stat"><span>Disponível</span><strong>${money(available)}</strong></div><div class="referral-stat"><span>Pago</span><strong>${money(paid)}</strong></div><div class="referral-stat"><span>Comissão padrão</span><strong>${Math.round(Number(refProfile.commission_rate||0)*100)}%</strong></div></div></section>`}

function adminPlanEditor(){return `<section class="owner-admin-card"><div><span class="eyebrow">ADMINISTRAÇÃO • PLANOS</span><h3>Gerenciamento de planos</h3><p>Valores e limites ficam no banco. Alterações aqui não exigem edição de código.</p></div><div class="admin-plan-list">${plans.map(p=>`<div class="admin-plan-row" data-admin-plan="${p.code}"><div><strong>${esc(p.name)}</strong><small style="display:block;color:var(--muted,#98a7ba)">${esc(p.code)}</small></div><label>Mensalidade<input data-f="price" type="number" step="0.01" min="0" value="${Number(p.price||0)}"></label><label>Implantação<input data-f="setup_price" type="number" step="0.01" min="0" value="${Number(p.setup_price||0)}"></label><label>Usuários<input data-f="user_limit" type="number" min="1" max="10000" value="${Number(p.user_limit||1)}"></label><label>Comissão %<input data-f="referral_rate" type="number" min="0" max="100" step="0.1" value="${Number(p.referral_rate||0)*100}"></label><div class="admin-switches"><label><input data-f="is_active" type="checkbox" ${p.is_active?'checked':''}> Ativo</label><label><input data-f="is_public" type="checkbox" ${p.is_public?'checked':''}> Público</label></div><button class="ghost-btn" data-save-plan="${p.code}" type="button">Salvar</button></div>`).join('')}</div></section>`}

function adminAccessManager(){const options=adminUsers.filter(x=>x.role!=='dono').map(u=>{const s=subscriptionFor(u.user_id);return `<option value="${u.user_id}">${esc(u.email)}${s?` • ${esc(s.plan_code)} (${esc(s.status)})`:''}</option>`}).join('');const pOpts=plans.map(p=>`<option value="${p.code}">${esc(p.name)}</option>`).join('');const emailById=new Map(adminUsers.map(u=>[u.user_id,u.email]));return `<section class="owner-admin-card"><div><span class="eyebrow">ADMINISTRAÇÃO • ACESSOS</span><h3>Liberação manual de plano</h3><p>Use para PIX, dinheiro ou fechamento realizado fora do checkout. A liberação manual não interfere nas automações de pagamento.</p></div><form id="ownerAccessForm" class="owner-access-form"><label>Usuário<select id="ownerPlanUser" required><option value="">Selecione</option>${options}</select></label><label>Plano<select id="ownerPlanCode" required>${pOpts}</select></label><label>Dias<input id="ownerPlanDays" type="number" min="1" max="3650" value="30" required></label><label class="wide">Observação<input id="ownerPlanNote" placeholder="Ex.: pago via PIX fora do sistema"></label><button class="primary-btn" type="submit">Liberar</button><button class="ghost-btn" id="ownerExpirePlan" type="button">Encerrar</button></form><div class="access-history">${accessChanges.length?accessChanges.slice(0,12).map(c=>`<div class="access-history-row"><span>${esc(emailById.get(c.target_user_id)||c.target_user_id)}</span><span>${esc(c.to_plan_code||'Acesso limitado')}</span><span>${esc(c.source)}</span><span>${dateBR(c.created_at)}</span></div>`).join(''):'<div class="plans-empty">Nenhuma alteração de plano registrada.</div>'}</div></section>`}

function render(){const page=$('#subscriptionPage');if(!page||!user)return;page.innerHTML=`<div class="plans-shell">${currentAccessCard()}${planCards()}${referralBlock()}${isOwner()?`<div class="owner-admin">${adminPlanEditor()}${adminAccessManager()}</div>`:''}</div>`;syncSidebar();bindRendered()}
function syncSidebar(){const el=$('#sidebarUserRole');if(!el)return;el.textContent=isOwner()?'Conta dono':entitlement?.mode==='trial'?'Teste 14 dias':entitlement?.plan_name||'Acesso limitado'}

async function savePlan(code,button){const row=button.closest('[data-admin-plan]');if(!row)return;const val=f=>row.querySelector(`[data-f="${f}"]`);const payload={price:Number(val('price').value||0),setup_price:Number(val('setup_price').value||0),user_limit:Number(val('user_limit').value||1),referral_rate:Number(val('referral_rate').value||0)/100,is_active:val('is_active').checked,is_public:val('is_public').checked,updated_at:new Date().toISOString()};button.disabled=true;const {error}=await supabase.from('ai_subscription_plans').update(payload).eq('code',code);button.disabled=false;if(error)return toast(error.message,'error');toast('Plano atualizado.');await loadCore();render()}
async function grantPlan(e){e.preventDefault();const uid=$('#ownerPlanUser').value,code=$('#ownerPlanCode').value,days=Number($('#ownerPlanDays').value||30),note=$('#ownerPlanNote').value.trim();if(!uid)return toast('Selecione um usuário.','error');const {error}=await supabase.rpc('owner_set_user_plan',{p_user_id:uid,p_plan_code:code,p_days:days,p_note:note||null});if(error)return toast(error.message,'error');toast('Plano liberado manualmente.');await loadCore();render()}
async function expirePlan(){const uid=$('#ownerPlanUser')?.value;if(!uid)return toast('Selecione um usuário.','error');if(!confirm('Encerrar o plano ativo deste usuário e devolver ao acesso limitado?'))return;const note=$('#ownerPlanNote')?.value.trim()||'Encerrado manualmente pelo dono';const {error}=await supabase.rpc('owner_expire_user_plan',{p_user_id:uid,p_note:note});if(error)return toast(error.message,'error');toast('Acesso pago encerrado.');await loadCore();render()}

function bindRendered(){document.querySelectorAll('[data-save-plan]').forEach(b=>b.addEventListener('click',()=>savePlan(b.dataset.savePlan,b)));$('#ownerAccessForm')?.addEventListener('submit',grantPlan);$('#ownerExpirePlan')?.addEventListener('click',expirePlan);$('#copyReferral')?.addEventListener('click',async()=>{const v=$('#referralLink')?.value||'';try{await navigator.clipboard.writeText(v);toast('Link de indicação copiado.')}catch{const i=$('#referralLink');i?.select();document.execCommand('copy');toast('Link de indicação copiado.')}});document.querySelectorAll('[data-plan-action]').forEach(b=>b.addEventListener('click',()=>{const p=plans.find(x=>x.code===b.dataset.planAction);toast(`Checkout Transparente de ${p?.name||'plano'} será aberto aqui. A integração de pagamento não usará assinatura recorrente no cartão.`)}))}

async function initSession(session){user=session?.user||null;if(!user)return;await captureReferral();await loadCore();render()}

ensureStyles();const {data:{session}}=await supabase.auth.getSession();await initSession(session);supabase.auth.onAuthStateChange((_e,s)=>setTimeout(()=>initSession(s),0));
